#======================================================================
# Project settings
#======================================================================

branches:
  only:
      - master

language: c

compiler:
  - gcc
  - clang

script:
  - autoreconf
  - ./configure
  - make
  - make install

#======================================================================
# Notifications
#======================================================================
notifications:
  email:
    recipients: tbrown@freeshell.org
    on_success: change
    on_failure: always


