branches:
  only:
      - master

language: c

dist: xenial

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y libcurl4-gnutls-dev libgpgme11-dev libxml2-dev

script:
  - autoreconf
  - ./configure
  - make

notifications:
  email:
    recipients: tbrown@freeshell.org
    on_success: change
    on_failure: always


